FROM golang:1.23.4

# Install necessary build tools
RUN apk add --no-cache gcc musl-dev

WORKDIR /build

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application with optimizations
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags="-w -s" \
    -o main ./src/cmd/api